language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true

jobs:
  include:
    - stage: build-deploy
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn && GIT_USER="${GH_NAME}" yarn deploy
    - stage: release
      script:
        - npx semantic-release